const ADMIN_CODE = "MHI-ADMIN-FRIDAY-2026";
const GAMES = {
  Trivia:[{type:"choice",q:"What is a movie preview called?",a:["Trailer","Receipt","Spreadsheet","Invoice"],c:0},{type:"choice",q:"What do you call the music from a movie?",a:["Soundtrack","Memo","Ledger","Subtitle"],c:0},{type:"choice",q:"Which is a movie genre?",a:["Comedy","Keyboard","Stapler","Calendar"],c:0},{type:"choice",q:"What is a sequel?",a:["A follow-up movie","A snack","A theater chair","A poster only"],c:0},{type:"choice",q:"Who acts in movies?",a:["Actor","Mechanic only","Cashier only","Pilot only"],c:0}],
  Emoji:[{type:"choice",q:"Guess: 🦁👑",a:["The Lion King","Frozen","Jaws","Cars"],c:0},{type:"choice",q:"Guess: 🧊👸❄️",a:["Frozen","Titanic","Up","Shrek"],c:0},{type:"choice",q:"Guess: 🐠🌊🔍",a:["Finding Nemo","Cars","Rocky","Scream"],c:0},{type:"choice",q:"Guess: 🧸🤠🚀",a:["Toy Story","Jaws","Avatar","Grease"],c:0},{type:"choice",q:"Guess: 🧌🫏👸",a:["Shrek","Titanic","Up","Coco"],c:0}],
  Scramble:[{type:"typed",q:"Unscramble: MLIF",answer:"film"},{type:"typed",q:"Unscramble: POCORPN",answer:"popcorn"},{type:"typed",q:"Unscramble: CESEN",answer:"scene"},{type:"typed",q:"Unscramble: POLT",answer:"plot"},{type:"typed",q:"Unscramble: COTAR",answer:"actor"}],
  SelectAll:[{type:"selectAll",q:"Select all movie snacks.",a:["Popcorn","Candy","Soda","Keyboard"],c:[0,1,2]},{type:"selectAll",q:"Select all movie jobs.",a:["Director","Actor","Editor","Printer"],c:[0,1,2]},{type:"selectAll",q:"Select all genres.",a:["Horror","Comedy","Drama","Stapler"],c:[0,1,2]},{type:"selectAll",q:"Select all movie terms.",a:["Scene","Plot","Trailer","Receipt"],c:[0,1,2]}],
  Matching:[{type:"matching",q:"Match the terms.",pairs:[["Trailer","Preview"],["Genre","Type"],["Actor","Performer"],["Credits","Worker list"],["Scene","Movie section"]]}],
  Kahoot:[{type:"choice",q:"Kahoot: Which is a movie award?",a:["Oscar","Receipt","Stapler","Keyboard"],c:0},{type:"choice",q:"Kahoot: Which is a movie job?",a:["Director","Dentist only","Bank teller only","Pilot only"],c:0},{type:"choice",q:"Kahoot: Which is a theater snack?",a:["Popcorn","Printer ink","Notebook","Mouse"],c:0},{type:"choice",q:"Kahoot: Which means first showing?",a:["Premiere","Invoice","Spreadsheet","Receipt"],c:0},{type:"choice",q:"Kahoot: Which is a preview?",a:["Trailer","Credits","Payroll","Calendar"],c:0}]
};
let player="",active=[],index=0,score=0,selected=new Set();const $=id=>document.getElementById(id);
function kahootOpen(){return localStorage.getItem("mhiKahootOpen")==="true";}function updateKahootStatus(){$("kahootStatus").textContent=kahootOpen()?"Kahoot is OPEN":"Kahoot is CLOSED";}
function pickGame(){const g=$("gameSelect").value;if(g==="Kahoot"&&!kahootOpen()){alert("Kahoot is closed. Admin must open it first.");return null;}if(g==="Random"){const allowed=Object.keys(GAMES).filter(x=>x!=="Kahoot");return Object.values(Object.fromEntries(allowed.map(k=>[k,GAMES[k]]))).flat().sort(()=>Math.random()-.5).slice(0,7);}return [...GAMES[g]].sort(()=>Math.random()-.5).slice(0,7);}
function start(){player=$("playerName").value.trim()||"Guest";active=pickGame();if(!active)return;index=0;score=0;$("entryPanel").classList.add("hidden");$("activePanel").classList.remove("hidden");render();}
function render(){const q=active[index];$("questionText").textContent=q.q;$("answers").innerHTML="";$("matchingBox").innerHTML="";$("typedBox").classList.add("hidden");$("matchingBox").classList.add("hidden");$("nextBtn").disabled=true;$("feedback").textContent=`Score: ${score}`;selected=new Set();if(q.type==="choice")q.a.forEach((answer,i)=>{const btn=document.createElement("button");btn.className="answer-btn";btn.textContent=answer;btn.onclick=()=>answer(i===q.c,btn);$("answers").appendChild(btn);});if(q.type==="typed")$("typedBox").classList.remove("hidden");if(q.type==="selectAll"){q.a.forEach((answer,i)=>{const btn=document.createElement("button");btn.className="answer-btn";btn.textContent=answer;btn.onclick=()=>{if(selected.has(i)){selected.delete(i);btn.classList.remove("correct");}else{selected.add(i);btn.classList.add("correct");}};$("answers").appendChild(btn);});const submit=document.createElement("button");submit.textContent="Submit Selected";submit.onclick=()=>answer([...selected].sort().join(",")===[...q.c].sort().join(","));$("answers").appendChild(submit);}if(q.type==="matching"){$("matchingBox").classList.remove("hidden");const right=q.pairs.map(p=>p[1]).sort(()=>Math.random()-.5);q.pairs.forEach(pair=>{const row=document.createElement("div");row.className="match-row";const left=document.createElement("strong");left.textContent=pair[0];const sel=document.createElement("select");sel.dataset.correct=pair[1];sel.innerHTML=`<option value="">Choose</option>`+right.map(r=>`<option value="${r}">${r}</option>`).join("");row.appendChild(left);row.appendChild(sel);$("matchingBox").appendChild(row);});const submit=document.createElement("button");submit.textContent="Submit Matching";submit.onclick=()=>answer([...document.querySelectorAll("#matchingBox select")].every(s=>s.value===s.dataset.correct));$("matchingBox").appendChild(submit);}}
function submitTyped(){const q=active[index];const guess=$("typedAnswer").value.trim().toLowerCase();if(!guess)return alert("Type an answer first.");$("typedAnswer").value="";answer(guess===q.answer.toLowerCase());}
function answer(correct,btn){[...document.querySelectorAll(".answer-btn")].forEach(b=>b.disabled=true);if(btn)btn.classList.add(correct?"correct":"wrong");if(correct)score+=10;$("feedback").textContent=correct?`Correct! Score: ${score}`:`Not quite. Score: ${score}`;$("nextBtn").disabled=false;}
function next(){index++;if(index<active.length)return render();score+=5;saveScore();$("questionText").textContent=`Game complete! Final score: ${score}`;$("answers").innerHTML="";$("typedBox").classList.add("hidden");$("matchingBox").classList.add("hidden");$("nextBtn").disabled=true;$("entryPanel").classList.remove("hidden");}
function saveScore(){const scores=JSON.parse(localStorage.getItem("mhiFunScores")||"[]");scores.push({name:player,score,date:new Date().toLocaleDateString(),game:$("gameSelect").value});localStorage.setItem("mhiFunScores",JSON.stringify(scores.slice(-100)));updateLeaderboard();}
function updateLeaderboard(){const scores=JSON.parse(localStorage.getItem("mhiFunScores")||"[]").sort((a,b)=>b.score-a.score).slice(0,20);$("leaderboard").innerHTML="";scores.forEach(s=>{const li=document.createElement("li");li.innerHTML=`<strong>${s.name}</strong> — ${s.score} pts<br><small>${s.game} • ${s.date}</small>`;$("leaderboard").appendChild(li);});}
function adminSetKahoot(open){if($("funAdminCode").value!==ADMIN_CODE)return alert("Invalid admin code.");localStorage.setItem("mhiKahootOpen",open?"true":"false");updateKahootStatus();}
function resetScores(){localStorage.removeItem("mhiFunScores");updateLeaderboard();}
$("startBtn").onclick=start;$("submitTypedBtn").onclick=submitTyped;$("nextBtn").onclick=next;$("resetBtn").onclick=resetScores;$("openKahootBtn").onclick=()=>adminSetKahoot(true);$("closeKahootBtn").onclick=()=>adminSetKahoot(false);updateLeaderboard();updateKahootStatus();
